name: build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  LM_LICENSE_FILE: "$GITHUB_WORKSPACE/tools/mwccarm/license.dat"
  CC: gcc-10
  CXX: g++-10
  COMPARE: 0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Update and Install Software
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt -y --allow-downgrades install libpng-dev build-essential cmake python3-pip python3-venv git autoconf gcc-arm-none-eabi pkg-config curl

      - name: Checkout Repo (decomp)
        uses: actions/checkout@v4
        with:
          repository: "BluRosie/pokeheartgold"
          path: "pokeheartgold"

      - name: Checkout Your Repo (hg-engine)
        uses: actions/checkout@v4
        with:
          path: "hg-engine"
          submodules: recursive

      - name: Build hg-engine
        run: |
          mkdir -p $GITHUB_WORKSPACE/pokeheartgold/build/heartgold.us
          cd $GITHUB_WORKSPACE/pokeheartgold
          make pokeheartgold.us.nds || true
          mkdir -p $GITHUB_WORKSPACE/hg-engine/build/heartgold.us
          cp build/heartgold.us/pokeheartgold.us.nds $GITHUB_WORKSPACE/hg-engine/rom.nds
          cd $GITHUB_WORKSPACE/hg-engine
          unset CC
          unset CXX
          make AUTO_TEST=Y -j$(nproc)

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-rom
          path: hg-engine/test.nds
