name: build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  LM_LICENSE_FILE: "$GITHUB_WORKSPACE/tools/mwccarm/license.dat"
  CC: gcc-10
  CXX: g++-10
  COMPARE: 0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Update and Install Software
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt -y --allow-downgrades install libpng-dev build-essential cmake python3-pip python3-venv git autoconf gcc-arm-none-eabi pkg-config curl

      - name: Checkout Your Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Custom Retiled Base From Google Drive
        run: |
        curl -L "https://docs.google.com/uc?export=download&id=1gjnGZxCA_6P8wSgsynuAFV1bMUnT0HL5" -o $GITHUB_WORKSPACE/rom.NDS
        
               


      - name: Restore Python cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-hg-engine-venv-${{ hashFiles('requirements.txt') }}

      - name: Restore tool cache
        uses: actions/cache@v4
        with:
          path: |
            tools/ENCODE_IMG
            tools/adpcm-xq
            tools/armips
            tools/msgenc
            tools/ndstool
            tools/nitrogfx
            tools/ntrWavTool.py
            tools/o2narc
          key: ${{ runner.os }}-hg-engine-tools-${{ hashFiles('Makefile', 'tools/source/**') }}

      - name: Build hg-engine
        run: |
          unset CC
          unset CXX
          make AUTO_TEST=Y -j$(nproc)

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-rom
          path: test.nds
